<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationsWithAdverts($limit){
        $qb = $this
            ->createQueryBuilder('a')
            ->leftJoin('a.adverts', 'adv')
            ->addSelect('adv')
            ->setMaxResults($limit);

        return $qb
            ->getQuery()
            ->getResult();

    }
}
